use_frameworks!

target 'iADSB_Example' do
  pod 'iADSB', :path => '../'
  pod 'ObjectiveWMM', git: 'git@github.com:ckhsponge/ObjectiveWMM.git', branch: 'ckhsponge/cocoapod'
  pod 'Starscream', '~> 3.0.2'
#  pod 'ObjectiveWMM', :path => '../../ObjectiveWMM'

  target 'iADSB_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
